### PR TITLE
v2.8 staging to master merge

### PR DESCRIPTION
**Pull request by manuwelakanade-GSLAB**
v2.8 staging to master merge

### CODE REVIEW

**Comment by manuwelakanade-GSLAB** [comment]
Hi @JosephPJordan : Can you please merge the staging to master commit. Thank you.

**Comment by manuwelakanade-GSLAB** [comment]
Hi @JosephPJordan : Can you please merge the staging to master commit. Thank you.

**Review by JosephPJordan — APPROVED** [review]

**Comment by JosephPJordan** [comment]
Approved, but waiting on checks to be completed apparently

**Comment by JosephPJordan** [comment]
@manuwelakanade-GSLAB, should I merge the request as an admin even though the 'check' hasn't passed?

**Comment by manuwelakanade-arista** [comment]
Hi @JosephPJordan : I'm not sure what those checks are which are pending and I'm unaware of the consequence of merging the PR before the checks pass. Hence I'm unable to answer whether merging this PR is okay. Will anybody be able to help us about these Travis CI checks and why they are pending? Thank you.

**Comment by manuwelakanade-GSLAB** [comment]
Hi @JosephPJordan : I'm not sure what those checks are which are pending and I'm unaware of the consequence of merging the PR before the checks pass. Hence I'm unable to answer whether merging this PR is okay. Will anybody be able to help us about these Travis CI checks and why they are pending? Thank you.

**Comment by JosephPJordan** [comment]
@manuwelakanade-GSLAB, i'm looking into this on this side, there seems to be a disconnect between the repo and Travis.  I'm waiting on responses.

**Comment by JosephPJordan** [comment]
@manuwelakanade-GSLAB, got it sorted, this repo dropped out of the travis pipeline for some reason (as did a couple others).  I made a fix to the release notes file directly in staging, as a repeated word was preventing the pipeline from succeeding. Should be good to go now.

**Comment by manuwelakanade-GSLAB** [comment]
Thanks for the merge @JosephPJordan !!

**Pull request merged**
