### PR TITLE
v2.7 staging to master 

### PR DESCRIPTION
**Pull request by manuwelakanade-GSLAB**
v2.7 staging to master

### CODE REVIEW

**Comment by manuwelakanade-GSLAB** [comment]
Hi @JosephPJordan : I have created a merge request for master branch (Same changes as #91). Please review and merge. Thank you!

**Review by JosephPJordan — APPROVED** [review]

**Comment by JosephPJordan** [comment]
@manuwelakanade-GSLAB, approved, just waiting for the checks to pass now

**Comment by JosephPJordan** [comment]
@manuwelakanade-GSLAB, not sure why the check has not completed, it's been an hour

**Comment by manuwelakanade-GSLAB** [comment]
Hi @JosephPJordan : Can this pull request be merged soon or is there any issue with the PR. Checking since 2.7 version of the app is already on its way for release. Thank you.

+ @payalsin

**Pull request merged**
